import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'

import { cn } from '~/common/utils/cn'

import { Providers } from './_providers/Providers'
import './globals.css'

const notoSans = Noto_Sans({ variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(notoSans.variable, 'antialiased')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
