import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Layout } from '~/common/layout'
import { Providers } from '~/common/providers'
import { cn } from '~/common/utils/cn'

import './globals.css'

const inter = Inter({ variable: '--font-sans', subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang='en'>
      <body className={cn(inter.variable, 'antialiased')}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  )
}
