/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../app/routes/__root'
import { Route as AuthRouteImport } from './../app/routes/_auth'
import { Route as IndexRouteImport } from './../app/routes/index'
import { Route as AuthReviewsRouteImport } from './../app/routes/_auth/reviews'
import { Route as AuthOrdersRouteImport } from './../app/routes/_auth/orders'
import { Route as AuthDashboardRouteImport } from './../app/routes/_auth/dashboard'
import { Route as AuthCustomersRouteImport } from './../app/routes/_auth/customers'
import { Route as AuthProductsIndexRouteImport } from './../app/routes/_auth/products/index'
import { Route as AuthCategoriesIndexRouteImport } from './../app/routes/_auth/categories/index'
import { Route as AuthProductsFormRouteImport } from './../app/routes/_auth/products/form'
import { Route as AuthCategoriesSlugRouteImport } from './../app/routes/_auth/categories/$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReviewsRoute = AuthReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesIndexRoute = AuthCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsFormRoute = AuthProductsFormRouteImport.update({
  id: '/products/form',
  path: '/products/form',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesSlugRoute = AuthCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/orders': typeof AuthOrdersRoute
  '/reviews': typeof AuthReviewsRoute
  '/categories/$slug': typeof AuthCategoriesSlugRoute
  '/products/form': typeof AuthProductsFormRoute
  '/categories/': typeof AuthCategoriesIndexRoute
  '/products/': typeof AuthProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/orders': typeof AuthOrdersRoute
  '/reviews': typeof AuthReviewsRoute
  '/categories/$slug': typeof AuthCategoriesSlugRoute
  '/products/form': typeof AuthProductsFormRoute
  '/categories': typeof AuthCategoriesIndexRoute
  '/products': typeof AuthProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/customers': typeof AuthCustomersRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/reviews': typeof AuthReviewsRoute
  '/_auth/categories/$slug': typeof AuthCategoriesSlugRoute
  '/_auth/products/form': typeof AuthProductsFormRoute
  '/_auth/categories/': typeof AuthCategoriesIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/orders'
    | '/reviews'
    | '/categories/$slug'
    | '/products/form'
    | '/categories/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/orders'
    | '/reviews'
    | '/categories/$slug'
    | '/products/form'
    | '/categories'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/customers'
    | '/_auth/dashboard'
    | '/_auth/orders'
    | '/_auth/reviews'
    | '/_auth/categories/$slug'
    | '/_auth/products/form'
    | '/_auth/categories/'
    | '/_auth/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reviews': {
      id: '/_auth/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthReviewsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/': {
      id: '/_auth/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthCategoriesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/form': {
      id: '/_auth/products/form'
      path: '/products/form'
      fullPath: '/products/form'
      preLoaderRoute: typeof AuthProductsFormRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/$slug': {
      id: '/_auth/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof AuthCategoriesSlugRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCustomersRoute: typeof AuthCustomersRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthReviewsRoute: typeof AuthReviewsRoute
  AuthCategoriesSlugRoute: typeof AuthCategoriesSlugRoute
  AuthProductsFormRoute: typeof AuthProductsFormRoute
  AuthCategoriesIndexRoute: typeof AuthCategoriesIndexRoute
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCustomersRoute: AuthCustomersRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthReviewsRoute: AuthReviewsRoute,
  AuthCategoriesSlugRoute: AuthCategoriesSlugRoute,
  AuthProductsFormRoute: AuthProductsFormRoute,
  AuthCategoriesIndexRoute: AuthCategoriesIndexRoute,
  AuthProductsIndexRoute: AuthProductsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
